remote_theme: samarsault/texture

# Site settings
title: Venky's Blog
description: A blog about technology, programming, and personal experiences
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://venkyr.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Texture theme settings
texture:
  title: Venky's Blog
  tagline: I make, therefore I am.
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true
  navigation:
    - title: Home
      url: "/"
  social_links:
    github: venkyr
    linkedIn: in/venkyraju
  footer_text: "Built with ❤️ using Jekyll and Texture theme"

# Show post excerpts on the home page
show_excerpts: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore 