title: My Blog
email: your-email@example.com
description: >-
  Welcome to my blog where I share my thoughts and experiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://venkyr.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore 